baseURL = "https://wzhuoqun.github.io/"
languageCode = "en-us"
title = "my resume"
theme = "PaperMod"

[params]
  ShowBreadCrumbs = true
  ShowPostNavLinks = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
