baseURL = "https://wzhuoqun.github.io/"
languageCode = "en-us"
title = "my resume"
theme = "PaperMod"

[params]
  ShowBreadCrumbs = true
  ShowPostNavLinks = true

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3

[caches]
  [caches.images]
    dir = ':cacheDir/images'
